# conformance_matrix.mojo — the property COMBINATIONS no fixture exhibits.
#
# WHY THIS EXISTS. fixture_census found five pairs that no .pipe.bin carries
# together even though each half is well covered alone:
#
#     multi-item + trie-miss     multi-item + scrolled     paged + trie-miss
#     wrapped + scrolled         trie-miss + scrolled
#
# A pair covered only separately proves nothing about the pair. That is not a
# hypothetical: item resolution hid from twelve suites because "multi-item" and
# "paged" were each covered and never together — paginate is the only kernel that
# resolves an item per thread, and it early-returns unless the item is paged.
#
# CONSTRUCTED TOPOLOGIES CANNOT USE THE ORACLE. A .pipe.bin carries expected
# values generated by the JS reference; an arena built here has none. So this
# suite checks INVARIANTS that must hold for any input whatsoever — properties of
# the pipeline's own output, not a comparison against a recorded answer. That is
# a different kind of evidence from conformance.mojo's bit-exactness and it is
# the kind available here.
#
# DISCRIMINABILITY IS THE POINT. Items get DISTINCT origins and MIXED page modes,
# because same-origin items make a wrong item resolution a no-op and an all-paged
# or all-unpaged run makes a mis-resolution invisible. Covering a property is not
# the same as being able to observe it.
#
# ENGAGEMENT (added 2026-09-02). The five invariants are SELF-CONSISTENT — they
# compare the pipeline's output against itself — so a cell whose property never
# occurred passes all five silently. check() now asserts each cell exercised what
# its label claims. On its first run it failed 16 of the 48: paging applies to ODD
# items only (for a mixed run), and the items=1 column has no odd item, so every
# items=1 x page cell carried a paged label over an unpaged run. build_items now
# pages item 0 when count == 1.
#
# Run: mojo run -I engine --fp-mode contract=off engine/conformance_matrix.mojo \
#          engine/fixtures/repo-file.pipe.bin

from std.sys import argv
from glyph_schema import LC_STRIDE, LC_ROW, LC_COL
from glyph_pipeline import (
    run_pipeline, Item, Trie, F_LEADER, F_RENDERED, F_MISSING, page_active,
)
from fixture_io import load_pipe_fixture

comptime MAX_PRINTED = 6


def build_corpus(n: Int, with_misses: Bool) -> List[UInt8]:
    """ASCII, optionally salted with codepoints the trie does not carry.

    The salt is spread every 7 bytes so misses land in EVERY shard rather than
    clustering — repo-file's 7 misses all fall in one shard, which is why shard
    concatenation order could be reversed without any suite noticing."""
    var b = List[UInt8](unsafe_uninit_length=n)
    for i in range(n):
        if with_misses and (i % 7) == 0:
            b[i] = UInt8(1 + (i % 26))          # control range: absent from the trie
        elif (i % 23) == 22:
            b[i] = 10                            # newline, so rows advance
        else:
            b[i] = UInt8(97 + (i % 26))
    return b^


def build_items(n: Int, count: Int, wrap: Int, page: Int, scroll: Bool) -> List[Item]:
    """`count` items tiling [0, n) with DISTINCT origins and MIXED page modes.

    page: 0 none, 1 row-paged, 2 column-paged. When nonzero, only the ODD items
    are paged — a mixed run, so a thread landing on the wrong item crosses a
    paged/unpaged boundary and the defect surfaces as a written-vs-not difference
    rather than as two similar numbers."""
    var items = List[Item]()
    var per = n // count
    for i in range(count):
        var it = Item()
        it.byte_start = i * per
        it.byte_count = per if i < count - 1 else n - i * per
        it.line_height = 1.0 + Float64(i) * 0.25     # distinct
        it.origin_x = Float64(i) * 11.0              # distinct
        it.origin_y = Float64(i) * 101.0             # distinct
        it.origin_z = Float64(i) * 3.0               # distinct
        it.wrap_width = wrap
        it.z_step = 0.5
        # ODD items only, so a run is MIXED and a thread landing on the wrong
        # item crosses a paged/unpaged boundary. But a ONE-item run has no odd
        # item and so paged nothing at all — 16 of the 48 cells carried a paged
        # label over an unpaged run until the engagement check above caught it
        # (2026-09-02). With a single item there is no mixture to preserve, so
        # all-paged is what "page=N" can honestly mean there.
        if page != 0 and (count == 1 or (i % 2) == 1):
            it.has_page = True
            it.pages_wide = 2
            it.page_gap_x = 1.0
            it.band_stride_y = 2.0
            it.depth_per_band = 0.25
            if page == 1:
                it.page_rows = 4
            else:
                it.page_cols = 6
                it.depth_per_col = 0.125
            if scroll:
                it.scroll_rows = 2
        elif scroll and (i % 2) == 0:
            # scrolled WITHOUT a page — paginate's scroll-only path
            it.has_page = True
            it.scroll_rows = 2
        items.append(it^)
    return items^


def check(
    name: String, bytes: List[UInt8], trie: Trie, items: List[Item],
    want_wrap: Int, want_page: Int, want_scroll: Bool,
) -> Int:
    """Five invariants that hold for ANY input, plus the engagement check that
    says the cell exercised what its label claims. No oracle required."""
    var n = len(bytes)
    var r = run_pipeline(bytes, trie, items)
    var bad = 0

    # ── 0. ENGAGEMENT. The five invariants below are SELF-CONSISTENT: they compare
    #      the pipeline's output against itself, so a cell where the property under
    #      test never occurred passes all five with nothing said. That is exactly
    #      how real-kernels.pipe.bin advertised "wrapped AND paged at once" while
    #      its page bag was typo'd inert. A label is a claim; this is where the
    #      claim gets checked.
    #
    #      Added 2026-09-02 and it immediately failed 16 of the 48 cells: paging is
    #      applied to ODD items only (a mixed run makes a mis-resolution visible),
    #      and the items=1 column has no odd item, so every items=1 x page cell
    #      constructed an unpaged run under a paged label. build_items now pages
    #      item 0 when there is only one — a single-item run cannot be mixed, so
    #      all-paged is the honest reading of "page=N" there.
    var row_paged = 0
    var col_paged = 0
    var scrolled = 0
    for i in range(len(items)):
        if items[i].page_rows > 0:
            row_paged += 1
        if items[i].page_cols > 0:
            col_paged += 1
        if items[i].scroll_rows > 0:
            scrolled += 1
    if want_page == 1 and row_paged == 0:
        print("  ", name, "VACUOUS: labelled row-paged, no item has page_rows > 0")
        bad += 1
    if want_page == 2 and col_paged == 0:
        print("  ", name, "VACUOUS: labelled column-paged, no item has page_cols > 0")
        bad += 1
    if want_scroll and scrolled == 0:
        print("  ", name, "VACUOUS: labelled scrolled, no item has scroll_rows > 0")
        bad += 1
    # Every cell must carry misses, or invariant 1 (miss ORDER) tests an empty
    # list. NOTE the miss=0 label is a misnomer: the base corpus already yields
    # 111 misses against this trie and miss=1 raises it to 506 — the dimension
    # varies, it does not toggle.
    #      UNPROVEN, and marked so deliberately: unlike the other three below,
    #      this one has never fired. Making it fire needs a trie that resolves
    #      every byte of the corpus, which this suite has no way to build — it
    #      borrows its trie from whatever fixture is passed in. The condition is
    #      a direct read of a length so there is little room for it to be wrong,
    #      but that was equally true of the first wrap check, which could not
    #      fail for a reason no amount of staring revealed. Treat it as
    #      unverified until something makes it red.
    if len(r.misses) == 0:
        print("  ", name, "VACUOUS: no trie misses, so the miss-order invariant is empty")
        bad += 1
    # Wrapping engaged iff some rendered leader sits at a column past the wrap
    # width — that is the fold's own definition of having wrapped.
    # NOT `COL >= want_wrap`, which was the first thing written here and CANNOT
    # FAIL: COL is the RAW leader count within the source line, not col % wrap,
    # so it is satisfied by any line longer than the wrap width whether wrapping
    # ran or not — neutering wrap_width to 0 left it green. The fold's real
    # signature is arithmetic: a source line of length L occupies L//W + 1 rows,
    # so a wrapped item's maximum ROW exceeds its newline count and an unwrapped
    # item's cannot.
    if want_wrap > 0:
        var wrapped = False
        var observable = False
        for i in range(len(items)):
            if page_active(items[i]):
                continue          # paginate remaps rows; the count means nothing there
            var newlines = 0
            var max_row = 0
            var stop = items[i].byte_start + items[i].byte_count
            for id in range(items[i].byte_start, stop):
                if id >= n:
                    break
                if bytes[id] == 0x0A:
                    newlines += 1
                var f = Int(r.fl[id])
                if (f & F_LEADER) == 0 or (f & F_RENDERED) == 0:
                    continue
                var row = Int(r.lc[id * LC_STRIDE + LC_ROW])
                if row > max_row:
                    max_row = row
            if max_row > newlines:
                wrapped = True
                break
            observable = True
        # An ALL-PAGED cell has no item whose rows survive un-remapped, so the
        # output-side test above has nothing to look at. Falling back to a silent
        # pass there would reintroduce exactly the vacuity this check exists to
        # find, so assert the INPUT side instead: the corpus must contain a line
        # longer than the wrap width, or `wrap=N` could not have done anything to
        # it no matter what the fold did.
        if not observable:
            var run_len = 0
            for id in range(n):
                if bytes[id] == 0x0A:
                    run_len = 0
                else:
                    run_len += 1
                    if run_len > want_wrap:
                        wrapped = True
                        break
        if not wrapped:
            print("  ", name, "VACUOUS: labelled wrap=", want_wrap,
                  "but nothing wrapped and no line exceeds that width")
            bad += 1
    var printed = 0

    # ── 1. MISS ORDER. The shards' lists concatenate in shard order, which is byte
    #      order only if every shard's own list is byte-ordered and the shards tile
    #      ascending. V2's 1.44x rests entirely on that.
    var want_misses = 0
    for id in range(n):
        var f = Int(r.fl[id])
        if (f & F_LEADER) != 0 and (f & F_MISSING) != 0:
            want_misses += 1
    if len(r.misses) != want_misses:
        print("  ", name, "miss count", len(r.misses), "expected", want_misses)
        bad += 1
    var seen = 0
    for id in range(n):
        var f = Int(r.fl[id])
        if (f & F_LEADER) != 0 and (f & F_MISSING) != 0:
            if seen < len(r.misses):
                if r.misses[seen] != UInt32(Int(bytes[id])):
                    if printed < MAX_PRINTED:
                        print("  ", name, "miss[", seen, "] =", r.misses[seen],
                              "expected", Int(bytes[id]), "at byte", id)
                        printed += 1
                    bad += 1
            seen += 1

    # ── 2. THE ORD WITNESS, straight from the schema: ordToByte[byteStart + ord]
    #      must be the byte itself. Per ITEM, not per arena — ord resets each item,
    #      so this only means anything with more than one item.
    for i in range(len(items)):
        var start = items[i].byte_start
        var stop = start + items[i].byte_count
        for id in range(start, stop):
            if id >= n:
                break
            var f = Int(r.fl[id])
            if (f & F_LEADER) == 0 or (f & F_RENDERED) == 0:
                continue
            var ord = Int(r.wc[id])
            var q = start + ord
            if q < 0 or q >= n or Int(r.ord_to_byte[q]) != id:
                bad += 1
                if printed < MAX_PRINTED:
                    print("  ", name, "ord witness: item", i, "byte", id,
                          "ord", ord, "-> ordToByte[", q, "] =",
                          r.ord_to_byte[q] if q >= 0 and q < n else 0)
                    printed += 1

    # ── 3. ORDINALS ARE A PERMUTATION of [0, leaders) within each item. A wrong
    #      item boundary shows up here as a duplicate or a hole even when every
    #      position happens to look plausible.
    for i in range(len(items)):
        var start = items[i].byte_start
        var stop = start + items[i].byte_count
        var seen_ord = List[Bool](unsafe_uninit_length=(stop - start) if stop > start else 1)
        for k in range(len(seen_ord)):
            seen_ord[k] = False
        var count = 0
        for id in range(start, stop):
            if id >= n:
                break
            var f = Int(r.fl[id])
            if (f & F_LEADER) == 0 or (f & F_RENDERED) == 0:
                continue
            var ord = Int(r.wc[id])
            if ord < 0 or ord >= len(seen_ord) or seen_ord[ord]:
                bad += 1
                if printed < MAX_PRINTED:
                    print("  ", name, "ord not a permutation: item", i,
                          "byte", id, "ord", ord)
                    printed += 1
            else:
                seen_ord[ord] = True
            count += 1
        for k in range(count):
            if not seen_ord[k]:
                bad += 1
                if printed < MAX_PRINTED:
                    print("  ", name, "ord hole: item", i, "missing ord", k)
                    printed += 1
                break

    # ── 4. GAP BYTES stay defined — the fold-owned count lanes have no other
    #      writer, so an unwritten one is uninitialised memory.
    var claimed = List[Bool](unsafe_uninit_length=n)
    for i in range(n):
        claimed[i] = False
    for i in range(len(items)):
        for b in range(items[i].byte_start, items[i].byte_start + items[i].byte_count):
            if b >= 0 and b < n:
                claimed[b] = True
    for id in range(n):
        if claimed[id]:
            continue
        var co = id * LC_STRIDE
        if r.lc[co + LC_ROW] != 0 or r.lc[co + LC_COL] != 0 or r.wc[id] != 0:
            bad += 1
            if printed < MAX_PRINTED:
                print("  ", name, "gap byte", id, "has nonzero fold lanes")
                printed += 1
            break

    # ── 5. ROW IS NON-DECREASING in byte order within an item. Wrap and pages both
    #      write rows; a wrap/scroll interaction that mis-orders them shows here.
    for i in range(len(items)):
        if page_active(items[i]):
            continue        # paginate legitimately remaps rows onto pages
        var last = -1
        for id in range(items[i].byte_start, items[i].byte_start + items[i].byte_count):
            if id >= n:
                break
            var f = Int(r.fl[id])
            if (f & F_LEADER) == 0 or (f & F_RENDERED) == 0:
                continue
            var row = Int(r.lc[id * LC_STRIDE + LC_ROW])
            if row < last:
                bad += 1
                if printed < MAX_PRINTED:
                    print("  ", name, "row went backwards: item", i, "byte", id,
                          "row", row, "after", last)
                    printed += 1
                break
            last = row

    return bad


def main() raises:
    var args = argv()
    if len(args) < 2:
        print("usage: mojo run -I engine engine/conformance_matrix.mojo <fixture.pipe.bin>")
        return
    var fx = load_pipe_fixture(String(args[1]))
    var n = 3000
    var bad = 0
    var cases = 0

    # THE MATRIX. items x wrap x page x scroll x misses — every cell, including the
    # five pairs the corpus never carried together.
    var item_counts: List[Int] = [1, 3]
    var wraps: List[Int] = [0, 5]
    var pages: List[Int] = [0, 1, 2]
    for mi in range(2):
        var with_misses = mi == 1
        var bytes = build_corpus(n, with_misses)
        for ic in range(len(item_counts)):
            for wi in range(len(wraps)):
                for pi in range(len(pages)):
                    for si in range(2):
                        var scroll = si == 1
                        var items = build_items(
                            n, item_counts[ic], wraps[wi], pages[pi], scroll
                        )
                        var label = String("items=") + String(item_counts[ic])
                        label += " wrap=" + String(Int(wraps[wi]))
                        label += " page=" + String(pages[pi])
                        label += " scroll=" + String(1 if scroll else 0)
                        label += " miss=" + String(1 if with_misses else 0)
                        var b = check(
                            label, bytes, fx.trie, items,
                            wraps[wi], pages[pi], scroll,
                        )
                        cases += 1
                        if b != 0:
                            print("FAIL", label, "-", b, "defects")
                        bad += b

    if bad != 0:
        raise Error("matrix conformance failed")
    print("matrix conformance:", cases,
          "property combinations, all five census gaps covered, invariants hold")
