// GENERATED by tools/gen_schema.py from schema/glyph-identity.json.
// DO NOT EDIT — edit the schema and regenerate.
//
// For engine/fixtures/gen.mjs; the lanes come from the lists in the
// generator, so the corpus and the schema cannot disagree.

// ── THE FIXTURE FORMAT — frozen on disk (format v2), independent of the
// container layout above it. gen.mjs writes these lanes in THIS order.
export const FIXTURE_MEASURE_STRIDE = 8;
export const FIX_M_X = 0;
export const FIX_M_Y = 1;
export const FIX_M_Z = 2;
export const FIX_M_ADVANCE = 3;
export const FIX_M_HEIGHT = 4;
export const FIX_M_GLYPH_ID = 5;
export const FIX_M_BASE_X = 6;
export const FIX_M_LINE_ADV = 7;

export const FIXTURE_COUNT_STRIDE = 4;
export const FIX_C_ROW = 0;
export const FIX_C_COL = 1;
export const FIX_C_FLAGS = 2;
export const FIX_C_ORD = 3;
