//! Committed artifacts: rebuilt in scratch and byte-compared against the tree.

use std::path::Path;

use crate::manifest::{Artifact, Class, Manifest};
use crate::paths::{root, sh};

pub(crate) fn verify_committed(m: &Manifest) -> bool {
    let mut ok = true;
    for (name, a) in m.artifact.iter().filter(|(_, a)| a.class == Class::Committed) {
        if let Some(c) = &a.verify_cmd {
            let (good, out) = sh(c, &root());
            let last = out.lines().last().unwrap_or("").to_string();
            if good {
                println!("PASS  {name} — {last}");
            } else {
                println!("FAIL  {name} — {last}");
                ok = false;
            }
        } else if a.counts.is_some() {
            ok &= verify_corpus(name, a);
        } else if let Some(c) = &a.verify_scratch {
            ok &= verify_scratch(name, a, c);
        } else {
            println!("FAIL  {name} declares no way to verify it");
            ok = false;
        }
    }
    ok
}

/// Rebuild into a scratch dir and byte-compare. The committed files are never
/// touched, which is the difference between this and the gate it replaced.
fn verify_scratch(name: &str, a: &Artifact, cmd: &str) -> bool {
    let scratch = std::env::temp_dir().join(format!("glyph-verify-{name}"));
    let _ = std::fs::remove_dir_all(&scratch);
    if std::fs::create_dir_all(&scratch).is_err() {
        println!("FAIL  {name} — could not make a scratch dir");
        return false;
    }
    let (good, out) = sh(&cmd.replace("{scratch}", &scratch.to_string_lossy()), &root());
    if !good {
        println!("FAIL  {name} — rebuild errored: {}", out.lines().last().unwrap_or(""));
        return false;
    }
    for o in &a.outputs {
        let file = Path::new(o).file_name().unwrap();
        let (built, committed) = (scratch.join(file), root().join(o));
        if std::fs::read(&built).ok() != std::fs::read(&committed).ok() {
            println!("FAIL  {name} — {} differs from the committed asset", file.to_string_lossy());
            return false;
        }
    }
    println!("PASS  {name} — {} rebuilt BYTE-IDENTICAL to scratch", a.outputs.len());
    true
}

/// The corpus is regenerated in a COPY. The counts it is checked against are
/// declared in the manifest, never counted off the tree being checked — a
/// deleted case would otherwise lower both sides and stay green.
fn verify_corpus(name: &str, a: &Artifact) -> bool {
    let scratch = std::env::temp_dir().join("glyph-verify-corpus");
    let _ = std::fs::remove_dir_all(&scratch);
    let (good, out) = sh(
        &format!(
            "rm -rf {0} && mkdir -p {0} && cp -R engine/fixtures {0}/fixtures && cp engine/glyph_schema.mjs {0}/ \
             && rm -f {0}/fixtures/*.pipe.bin {0}/fixtures/*.bake.bin \
             && cd {0}/fixtures && node gen.mjs >/dev/null && node gen-bake.mjs >/dev/null",
            scratch.to_string_lossy()
        ),
        &root(),
    );
    if !good {
        println!("FAIL  {name} — a fixture generator errored; the corpus is not rebuildable");
        println!("      {}", out.lines().last().unwrap_or(""));
        return false;
    }
    let counts = a.counts.as_ref().unwrap();
    for (ext, want) in counts {
        let built: Vec<_> = glob::glob(&format!("{}/fixtures/*.{ext}.bin", scratch.to_string_lossy()))
            .map(|g| g.filter_map(Result::ok).collect())
            .unwrap_or_default();
        if built.len() as u32 != *want {
            println!(
                "FAIL  {name} — regenerated {} .{ext}.bin, build.toml declares {want} \
                 (a generator's case list changed; update the count deliberately)",
                built.len()
            );
            return false;
        }
        for b in &built {
            let committed = root().join("engine/fixtures").join(b.file_name().unwrap());
            if std::fs::read(b).ok() != std::fs::read(&committed).ok() {
                println!(
                    "FAIL  {name} — {} differs from the committed fixture",
                    b.file_name().unwrap().to_string_lossy()
                );
                return false;
            }
        }
    }
    let total: u32 = counts.values().sum();
    println!(
        "PASS  {name} — {total} fixtures ({}) regenerated BYTE-IDENTICAL in scratch; \
         counts declared in build.toml, not ls-derived",
        counts.iter().map(|(k, v)| format!("{v} {k}")).collect::<Vec<_>>().join(" + ")
    );
    true
}
