//! glyph3d-native — the renderer as a LIBRARY.
//!
//! The bin (`src/main.rs`) is the CLI shell: clap parsing, run-mode
//! dispatch, help text. Everything a second binary might want to link —
//! scenes, layout seams, the fold, picking, verbs, scene assembly — lives
//! here as `pub mod`s plus the shared assembly layer (`SceneChoice`,
//! `build_scene*`, engine helpers, `Op`, `parse_verb`).
//!
//! Why a lib target exists: the Zed-integration experiment links this crate
//! into the experiment workspace (`experiments/zedspike` and successors) so
//! one binary can hold both the renderer and Zed's language stack — see
//! `zed_integration_experiments/docs/seam.md`. The gated repo build is
//! unchanged (same code, same binary out of `main.rs`); only the experiment
//! workspace's lock ever sees Zed's dependency graph.
//!
//! Module map, contracts, and history: the crate doc in `main.rs` and the
//! per-module headers remain canonical.

pub mod atlas;
pub mod bake;
pub mod engine;
pub mod fixture;
pub mod fold;
pub mod glyph_trie;
pub mod gpu;
pub mod glyph_scene;
pub mod layout;
pub mod layout_mojo;
pub mod offscreen;
pub mod repo;
pub mod scan;
pub mod scene;
pub mod seam;
pub mod text;
pub mod windowed;

use std::path::{Path, PathBuf};

use glyph_scene::{CameraMode, GlyphScene, PickCommand, Verb};
use gpu::GpuContext;
// The seam is used by trait, not by concrete backend: swapping `MojoLayout`
// for the Rust one changes the constructor and nothing else here.
use layout::{LayoutGlyphs, VerifyLayout};
use scene::{Scene, SceneLike};

pub const OFFSCREEN_WIDTH: u32 = 1600;
pub const OFFSCREEN_HEIGHT: u32 = 1000;

/// Which scene a run mode builds.
pub enum SceneChoice {
    /// Stage A stress demo (1M colored quads).
    Demo,
    /// Stage C Slug text field: stage `file`, tiled `copies` times.
    Text { file: PathBuf, copies: u32, emoji_sheet: PathBuf },
    /// Stage E1: lay `file` out with the Mojo engine (real atlas trie) and
    /// render the engine's records through the same Slug glyph renderer.
    EngineText { file: PathBuf, trie: PathBuf, emoji_sheet: PathBuf },
    /// Stage E2: load a whole repository as a field of code pages — one group
    /// per file, one shared glyph arena, grid layout.
    Repo {
        dir: PathBuf,
        strategy: layout_mojo::Strategy,
        verify: bool,
        focus: Option<String>,
        /// How a wrap is spent. `Back` is the default: a wrapped line costs
        /// DEPTH rather than a row, which is the layout this renderer is for.
        /// `repo-wide` and `repo-zoom` are gated on it; `repo-down` keeps the
        /// other mode covered so making one default cannot silently retire the
        /// other.
        wrap_mode: fold::WrapMode,
        /// The wrap staircase's pitch (`--z-wrap-spacing`, default 0.15 —
        /// the web's `zWrapSpacing`). Carried alongside wrap_mode for the
        /// same reason: the baselines depend on the default, so the CLI
        /// layer pins it rather than letting RepoParams::default speak alone.
        z_wrap_spacing: f64,
        /// The colour-emoji sheet (`--emoji-sheet`; default the committed
        /// one). Every glyph scene loads it — the same handle the engine
        /// trie has, so swapping a sheet is a command-line act.
        emoji_sheet: PathBuf,
    },
}

/// The atlas directory shared by every mode (`<crate>/../assets/atlas`).
pub fn atlas_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../assets/atlas")
}

/// Stage E1: the engine's default trie — the REAL atlas mapping, generated by
/// `python3 tools/gen_real_trie.py` (not a conformance fixture).
pub fn default_engine_trie() -> PathBuf {
    atlas_dir().join("engine-trie.bin")
}

/// The colour-emoji sheet the renderer loads unless `--emoji-sheet` says
/// otherwise — `assets/atlas/emoji-sheet.bin`, baked by tools/gen_emoji_sheet.py.
pub fn default_emoji_sheet() -> PathBuf {
    atlas_dir().join("emoji-sheet.bin")
}

/// The engine layout params the renderer/cross-check use: unit cell height
/// (text::CELL_HEIGHT_WORLD) and the production line pitch. No wrap, no pages.
/// The same params at a chosen origin.
///
/// The origin exists as a parameter because a zero one is a BLIND SPOT. A Mojo
/// nightly was found miscompiling `ffi.mojo`'s descriptor read when built into
/// a test executable — an uninitialised read — while the same source built as
/// the shipping dylib was bit-exact. `ffi_selftest` catches that class, and for
/// a while it was the ONLY thing that did, because this cross-check laid every
/// item out at (0,0,0) and so never exercised the `origin_x` read at all: a
/// garbage value added to zero and compared against zero-plus-the-same-garbage
/// agrees with itself. One instrument covering a whole failure class is a
/// single point of failure, so `--engine-check` now runs a non-zero origin too.
pub fn engine_item_params_at(origin: [f64; 3]) -> layout::ItemParams {
    layout::ItemParams {
        line_height: (text::CELL_HEIGHT_WORLD * text::LINE_HEIGHT_FACTOR) as f64,
        origin_x: origin[0],
        origin_y: origin[1],
        origin_z: origin[2],
        ..Default::default()
    }
}

/// The one item `--engine-render` and `--engine-check` each lay out: the whole
/// file, production line pitch, flat default paint, group 0.
fn engine_item(bytes: &[u8]) -> layout::LayoutItem<'_> {
    engine_item_at(bytes, [0.0, 0.0, 0.0])
}

fn engine_item_at(bytes: &[u8], origin: [f64; 3]) -> layout::LayoutItem<'_> {
    layout::LayoutItem {
        bytes,
        params: engine_item_params_at(origin),
        group_id: 0,
        paint: layout::Paint::Flat(layout::DEFAULT_COLOR_PACKED),
    }
}

fn engine_backend(trie: &Path) -> layout_mojo::MojoLayout {
    let mut backend = layout_mojo::MojoLayout::new(layout_mojo::Strategy::Batched);
    backend
        .load_trie_file(trie)
        .expect("failed to load engine trie");
    backend
}

/// Lay one file out through the seam FOR RENDERING: instances in an arena plus
/// its placement. No records, no readback — this is the path a frame takes.
pub fn engine_layout(file: &Path, trie: &Path) -> (layout::GlyphArena, layout::ItemPlacement) {
    let bytes = std::fs::read(file).expect("failed to read engine input file");
    let mut backend = engine_backend(trie);
    let mut arena = layout::GlyphArena::new();
    let placements = backend
        .layout_items(&[engine_item(&bytes)], &mut arena)
        .expect("engine layout failed");
    (arena, placements[0])
}

/// Lay one file out through the seam FOR VERIFICATION: the wire records, which
/// `--engine-check` diffs lane by lane against the independent CPU reference.
/// This is the 36 B-per-source-byte readback the render path above does not
/// pay, asked for explicitly through `VerifyLayout` — see `layout.rs`.
pub fn engine_layout_records_at(
    file: &Path,
    trie: &Path,
    origin: [f64; 3],
) -> Vec<layout::GlyphRecord> {
    let bytes = std::fs::read(file).expect("failed to read engine input file");
    let mut backend = engine_backend(trie);
    let mut arena = layout::GlyphArena::new();
    let (placements, records) = backend
        .layout_items_recording(&[engine_item_at(&bytes, origin)], &mut arena)
        .expect("engine layout failed");
    assert_eq!(
        records.len() as u32, placements[0].record_count,
        "record copy count mismatch"
    );
    records
}

/// Build the chosen scene for a given color target format.
pub fn build_scene(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
) -> Box<dyn SceneLike> {
    // Offscreen path: never installs a UI probe (probe = false), so the
    // scene behaves exactly as pre-K.
    build_scene_impl(ctx, color_format, choice, camera_mode, cull, false).0
}

/// Stage K (K3): windowed scene construction. Same scenes as build_scene,
/// plus a debug-UI probe handle installed on the concrete GlyphScene BEFORE
/// type erasure — the egui Debug panel's read-back channel (windowed.rs
/// holds the scene as `Box<dyn SceneLike>`; fence 4 forbids SceneLike
/// changes). The demo scene has no probe (None).
pub fn build_scene_probed(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
) -> (Box<dyn SceneLike>, Option<glyph_scene::UiProbe>) {
    build_scene_impl(ctx, color_format, choice, camera_mode, cull, true)
}

fn build_scene_impl(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
    probe: bool,
) -> (Box<dyn SceneLike>, Option<glyph_scene::UiProbe>) {
    // Same construction order for both modes; only the probe install differs.
    let glyph = |scene: GlyphScene| {
        let mut scene = scene;
        let p = probe.then(|| scene.init_ui_probe());
        (Box::new(scene) as Box<dyn SceneLike>, p)
    };
    match choice {
        SceneChoice::Demo => (Box::new(Scene::new(ctx, color_format)), None),
        SceneChoice::Text { file, copies, emoji_sheet } => {
            let atlas = atlas::Atlas::load(ctx, emoji_sheet);
            let staged = text::stage_file(&atlas, file, *copies);
            log::info!(
                "staged {}: {} codepoints → {} glyph instances ({} copies, {} missing/bitmap)",
                file.display(),
                staged.codepoints_decoded,
                staged.glyphs_emitted,
                copies,
                staged.missing_or_bitmap,
            );
            glyph(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
        SceneChoice::EngineText { file, trie, emoji_sheet } => {
            let atlas = atlas::Atlas::load(ctx, emoji_sheet);
            let (arena, placement) = engine_layout(file, trie);
            log::info!(
                "engine-staged {}: {} records ({} blank/missing slots dropped)",
                file.display(),
                placement.record_count,
                placement.record_count - placement.slot_count,
            );
            let staged = text::stage_records(arena, &placement, &atlas.slot_ink);
            glyph(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
        SceneChoice::Repo {
            dir,
            strategy,
            verify,
            focus,
            wrap_mode,
            z_wrap_spacing,
            emoji_sheet,
        } => {
            let params = repo::RepoParams {
                wrap_mode: *wrap_mode,
                z_wrap_spacing: *z_wrap_spacing,
                ..Default::default()
            };
            let load = repo::load_repo(dir, &default_engine_trie(), &params, *strategy, *verify);
            load.print_stats();
            let atlas = atlas::Atlas::load(ctx, emoji_sheet);
            let staged = load.into_staged(focus.as_deref(), &atlas.slot_ink);
            glyph(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
    }
}

/// Stage G: one scripted operation (picks and verbs interleave in CLI order).
pub enum Op {
    Pick(PickCommand),
    Verb(Verb),
    /// Scripted Fly-camera pose: eye + yaw/pitch (RADIANS) — repro of
    /// oblique windowed camera states for --pick-px.
    CamPose([f32; 3], f32, f32),
    /// S3 spike: apply a Zed-sidecar highlight to instance colors (offscreen,
    /// before the first frame — same op-stream slot as picks/verbs).
    Highlight(PathBuf),
}

/// Parse a `--verb` string into a Verb (clap `value_parser`). Forms:
///   recolor-glyph `[rrggbb]`      recolor-line `[rrggbb]`
///   nudge-glyph dx dy `[dz]`      scale-glyph f
///   move-group dx dy dz         scale-group s
///   tint-group rrggbb           tint-cycle
///   hide-group | show-group | toggle-hidden
pub fn parse_verb(s: &str) -> Result<Verb, String> {
    let t: Vec<&str> = s.split_whitespace().collect();
    let usage = format!(
        "unknown/malformed --verb {s:?} — expected recolor-glyph|recolor-line|\
         nudge-glyph|scale-glyph|move-group|scale-group|tint-group|tint-cycle|\
         hide-group|show-group|toggle-hidden"
    );
    let f = |i: usize| -> Result<f32, String> {
        t.get(i)
            .and_then(|v| v.parse().ok())
            .ok_or_else(|| format!("--verb {s:?}: bad/missing float at position {i}"))
    };
    let hex = |i: usize| -> Result<[u8; 3], String> {
        let h = t
            .get(i)
            .ok_or_else(|| format!("--verb {s:?}: missing rrggbb at position {i}"))?
            .trim_start_matches('#');
        let v = u32::from_str_radix(h, 16)
            .map_err(|_| format!("--verb {s:?}: bad hex color {h:?}"))?;
        Ok([((v >> 16) & 0xFF) as u8, ((v >> 8) & 0xFF) as u8, (v & 0xFF) as u8])
    };
    Ok(match t.first().copied().unwrap_or("") {
        "recolor-glyph" => Verb::RecolorGlyph(if t.len() > 1 { hex(1)? } else { [255, 80, 80] }),
        "recolor-line" => Verb::RecolorLine(if t.len() > 1 { hex(1)? } else { [255, 213, 79] }),
        "nudge-glyph" => Verb::NudgeGlyph([f(1)?, f(2)?, if t.len() > 3 { f(3)? } else { 0.0 }]),
        "scale-glyph" => Verb::ScaleGlyph(f(1)?),
        "move-group" => Verb::MoveGroup([f(1)?, f(2)?, f(3)?]),
        "scale-group" => Verb::ScaleGroup(f(1)?),
        "tint-group" => {
            let [r, g, b] = hex(1)?;
            Verb::TintGroup([r as f32 / 255.0, g as f32 / 255.0, b as f32 / 255.0])
        }
        "tint-cycle" => Verb::TintCycle,
        "hide-group" => Verb::SetHidden(true),
        "show-group" => Verb::SetHidden(false),
        "toggle-hidden" => Verb::ToggleHidden,
        _ => return Err(usage),
    })
}
