//! glyph3d-native — native GPU port of the glyph3d-js code-visualization system.
//!
//! Stage A: windowed/offscreen shell + 1M-instance quad-field stress demo.
//! Stage C: Slug analytic-coverage glyph renderer (atlas loader, WGSL Slug
//!          pipeline, text staging) behind `--render-file` (the default scene).
//! Stage F: fly camera (windowed) + per-file CPU frustum/LOD culling with
//!          far-LOD backdrop quads — the repo field is interactive.
//!          `--no-cull` keeps the legacy full-field draws for A/B.
//! Stage G: CPU picking + live manipulation. `--pick-file/--pick-row/
//!          --pick-col/--pick-px` resolve file → row/col → char; `--verb`
//!          edits instances (recolor/nudge/scale glyph, recolor line) and
//!          groups (move/scale/tint/hide) with partial buffer uploads.
//!          Windowed: left click picks, h/g/t/x verbs, right-drag look.
//! Stage H: clap CLI (parity-tested), naga WGSL validation in `cargo test`,
//!          opt-in wgpu-profiler pass timings (GLYPH_PROFILE=1), encase
//!          layout assertions for the hand-mirrored WGSL lane maps.
//! Stage I: glam 0.30 → 0.33 (byte-identical under the full A/B suite);
//!          baseline views moved onto the immutable fixtures/baseline-view.txt.
//! Stage K: egui 0.36 overlay on the windowed renderer (K1: deps + plumbing
//!          with an empty UI; `--no-ui` gives exact pre-K windowed behavior).
//!
//! Run modes:
//!   (default) `[--render-file <path>] [--copies N]`
//!                                    windowed: text field, orbiting camera, FPS log.
//!   --demo                           windowed: Stage A quad-field demo.
//!   --screenshot <path.png> [--frames N] [--zoom F] [--render-file P] [--copies N] [--demo]
//!                                    offscreen: render N frames, write PNG, print
//!                                    timing, exit 0. Deterministic (fixed virtual clock).

mod atlas;
mod bake;
mod cli;
mod engine;
mod fixture;
mod fold;
mod glyph_trie;
mod layout;
mod layout_mojo;
mod gpu;
mod glyph_scene;
mod offscreen;
mod repo;
mod scan;
mod scene;
mod text;
mod windowed;

use std::path::{Path, PathBuf};

use clap::CommandFactory;
pub use cli::Op;
pub(crate) use cli::parse_verb;
use cli::{default_text_file, parse_cli, parse_cluster_mode, parse_present_mode, parse_strategy, parse_wrap_mode, Cli};
use glyph_scene::{CameraMode, GlyphScene};
use gpu::GpuContext;
// The seam is used by trait, not by concrete backend: swapping `MojoLayout`
// for the Rust one changes the constructor and nothing else here.
use layout::{LayoutGlyphs, VerifyLayout};
use scene::{Scene, SceneLike};

pub const OFFSCREEN_WIDTH: u32 = 1600;
pub const OFFSCREEN_HEIGHT: u32 = 1000;

/// Which scene a run mode builds.
pub enum SceneChoice {
    /// Stage A stress demo (1M colored quads).
    Demo,
    /// Stage C Slug text field: stage `file`, tiled `copies` times.
    Text { file: PathBuf, copies: u32, emoji_sheet: PathBuf, cluster_mode: fold::ClusterMode },
    /// Stage E1: lay `file` out with the Mojo engine (real atlas trie) and
    /// render the engine's records through the same Slug glyph renderer.
    EngineText { file: PathBuf, trie: PathBuf, emoji_sheet: PathBuf },
    /// Stage E2: load a whole repository as a field of code pages — one group
    /// per file, one shared glyph arena, grid layout.
    Repo {
        dir: PathBuf,
        strategy: layout_mojo::Strategy,
        verify: bool,
        focus: Option<String>,
        /// How a wrap is spent. `Back` is the default: a wrapped line costs
        /// DEPTH rather than a row, which is the layout this renderer is for.
        /// `repo-wide` and `repo-zoom` are gated on it; `repo-down` keeps the
        /// other mode covered so making one default cannot silently retire the
        /// other.
        wrap_mode: fold::WrapMode,
        /// The wrap staircase's pitch (`--z-wrap-spacing`, default 0.15 —
        /// the web's `zWrapSpacing`). Carried alongside wrap_mode for the
        /// same reason: the baselines depend on the default, so the CLI
        /// layer pins it rather than letting RepoParams::default speak alone.
        z_wrap_spacing: f64,
        /// The sequence pass on a repo load (`--cluster-mode`, default
        /// cluster since 2026-09-22). Same standing as wrap_mode: the
        /// baselines pin the default.
        cluster_mode: fold::ClusterMode,
        /// The colour-emoji sheet (`--emoji-sheet`; default the committed
        /// one). Every glyph scene loads it — the same handle the engine
        /// trie has, so swapping a sheet is a command-line act.
        emoji_sheet: PathBuf,
    },
}

pub fn atlas_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../assets/atlas")
}

/// Stage E1: the engine's default trie — the REAL atlas mapping, generated by
/// `python3 tools/gen_real_trie.py` (not a conformance fixture).
pub fn default_engine_trie() -> PathBuf {
    atlas_dir().join("engine-trie.bin")
}

/// The colour-emoji sheet the renderer loads unless `--emoji-sheet` says
/// otherwise — `assets/atlas/emoji-sheet.bin`, baked by tools/gen_emoji_sheet.py.
pub fn default_emoji_sheet() -> PathBuf {
    atlas_dir().join("emoji-sheet.bin")
}

/// The engine layout params the renderer/cross-check use: unit cell height
/// (text::CELL_HEIGHT_WORLD) and the production line pitch. No wrap, no pages.
/// The same params at a chosen origin.
///
/// The origin exists as a parameter because a zero one is a BLIND SPOT. A Mojo
/// nightly was found miscompiling `ffi.mojo`'s descriptor read when built into
/// a test executable — an uninitialised read — while the same source built as
/// the shipping dylib was bit-exact. `ffi_selftest` catches that class, and for
/// a while it was the ONLY thing that did, because this cross-check laid every
/// item out at (0,0,0) and so never exercised the `origin_x` read at all: a
/// garbage value added to zero and compared against zero-plus-the-same-garbage
/// agrees with itself. One instrument covering a whole failure class is a
/// single point of failure, so `--engine-check` now runs a non-zero origin too.
pub fn engine_item_params_at(origin: [f64; 3]) -> layout::ItemParams {
    layout::ItemParams {
        line_height: (text::CELL_HEIGHT_WORLD * text::LINE_HEIGHT_FACTOR) as f64,
        origin_x: origin[0],
        origin_y: origin[1],
        origin_z: origin[2],
        ..Default::default()
    }
}

/// The one item `--engine-render` and `--engine-check` each lay out: the whole
/// file, production line pitch, flat default paint, group 0.
fn engine_item(bytes: &[u8]) -> layout::LayoutItem<'_> {
    engine_item_at(bytes, [0.0, 0.0, 0.0])
}

fn engine_item_at(bytes: &[u8], origin: [f64; 3]) -> layout::LayoutItem<'_> {
    layout::LayoutItem {
        bytes,
        params: engine_item_params_at(origin),
        group_id: 0,
        paint: layout::Paint::Flat(layout::DEFAULT_COLOR_PACKED),
    }
}

fn engine_backend(trie: &Path) -> layout_mojo::MojoLayout {
    let mut backend = layout_mojo::MojoLayout::new(layout_mojo::Strategy::Batched);
    backend
        .load_trie_file(trie)
        .expect("failed to load engine trie");
    backend
}

/// Lay one file out through the seam FOR RENDERING: instances in an arena plus
/// its placement. No records, no readback — this is the path a frame takes.
fn engine_layout(file: &Path, trie: &Path) -> (layout::GlyphArena, layout::ItemPlacement) {
    let bytes = std::fs::read(file).expect("failed to read engine input file");
    let mut backend = engine_backend(trie);
    let mut arena = layout::GlyphArena::new();
    let placements = backend
        .layout_items(&[engine_item(&bytes)], &mut arena)
        .expect("engine layout failed");
    (arena, placements[0])
}

/// Lay one file out through the seam FOR VERIFICATION: the wire records, which
/// `--engine-check` diffs lane by lane against the independent CPU reference.
/// This is the 36 B-per-source-byte readback the render path above does not
/// pay, asked for explicitly through `VerifyLayout` — see `layout.rs`.
fn engine_layout_records_at(
    file: &Path,
    trie: &Path,
    origin: [f64; 3],
) -> Vec<layout::GlyphRecord> {
    let bytes = std::fs::read(file).expect("failed to read engine input file");
    let mut backend = engine_backend(trie);
    let mut arena = layout::GlyphArena::new();
    let (placements, records) = backend
        .layout_items_recording(&[engine_item_at(&bytes, origin)], &mut arena)
        .expect("engine layout failed");
    assert_eq!(
        records.len() as u32, placements[0].record_count,
        "record copy count mismatch"
    );
    records
}

/// Build the chosen scene for a given color target format.
pub fn build_scene(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
) -> Box<dyn SceneLike> {
    // Offscreen path: never installs a UI probe (probe = false), so the
    // scene behaves exactly as pre-K.
    build_scene_impl(ctx, color_format, choice, camera_mode, cull, false).0
}

/// Stage K (K3): windowed scene construction. Same scenes as build_scene,
/// plus a debug-UI probe handle installed on the concrete GlyphScene BEFORE
/// type erasure — the egui Debug panel's read-back channel (windowed.rs
/// holds the scene as `Box<dyn SceneLike>`; fence 4 forbids SceneLike
/// changes). The demo scene has no probe (None).
pub fn build_scene_probed(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
) -> (Box<dyn SceneLike>, Option<glyph_scene::UiProbe>) {
    build_scene_impl(ctx, color_format, choice, camera_mode, cull, true)
}

fn build_scene_impl(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
    probe: bool,
) -> (Box<dyn SceneLike>, Option<glyph_scene::UiProbe>) {
    // Same construction order for both modes; only the probe install differs.
    let glyph = |scene: GlyphScene| {
        let mut scene = scene;
        let p = probe.then(|| scene.init_ui_probe());
        (Box::new(scene) as Box<dyn SceneLike>, p)
    };
    match choice {
        SceneChoice::Demo => (Box::new(Scene::new(ctx, color_format)), None),
        SceneChoice::Text { file, copies, emoji_sheet, cluster_mode } => {
            let atlas = atlas::Atlas::load(ctx, emoji_sheet);
            let staged = text::stage_file(&atlas, file, *copies, *cluster_mode);
            log::info!(
                "staged {}: {} codepoints → {} glyph instances ({} copies, {} missing/bitmap)",
                file.display(),
                staged.codepoints_decoded,
                staged.glyphs_emitted,
                copies,
                staged.missing_or_bitmap,
            );
            let mut scene = GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull);
            // No pick context on this path, so the panel's cluster toggle
            // seeds from the choice directly — hand it the mode the scene
            // was staged with.
            scene.set_probe_cluster_mode(matches!(cluster_mode, fold::ClusterMode::Cluster));
            glyph(scene)
        }
        SceneChoice::EngineText { file, trie, emoji_sheet } => {
            let atlas = atlas::Atlas::load(ctx, emoji_sheet);
            let (arena, placement) = engine_layout(file, trie);
            log::info!(
                "engine-staged {}: {} records ({} blank/missing slots dropped)",
                file.display(),
                placement.record_count,
                placement.record_count - placement.slot_count,
            );
            let staged = text::stage_records(arena, &placement, &atlas.slot_ink);
            glyph(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
        SceneChoice::Repo {
            dir,
            strategy,
            verify,
            focus,
            wrap_mode,
            z_wrap_spacing,
            cluster_mode,
            emoji_sheet,
        } => {
            let params = repo::RepoParams {
                wrap_mode: *wrap_mode,
                z_wrap_spacing: *z_wrap_spacing,
                cluster_mode: *cluster_mode,
                ..Default::default()
            };
            let load = {
                let walk = repo::walk_repo(dir);
                // The device-resident arena: the FFI writes instances into
                // the same shared-storage buffer the shader reads. Direct
                // only (it's the strategy with the tail-write protocol), on
                // unified memory, when the buffer fits.
                let arena = if *strategy == layout_mojo::Strategy::Direct
                    && ctx.profile.backend == wgpu::Backend::Metal
                    && ctx.profile.mappable_primary_buffers
                    && walk.total_bytes > 0
                    && (walk.total_bytes * std::mem::size_of::<glyph_scene::GlyphInstance>()) as u64
                        <= ctx.profile.max_buffer_size
                {
                    glyph_scene::mapped_instance_arena(ctx, walk.total_bytes)
                } else {
                    layout::GlyphArena::new()
                };
                repo::load_repo_from_walk(dir, walk, &default_engine_trie(), &params, *strategy, *verify, arena)
            };
            load.print_stats();
            let atlas = atlas::Atlas::load(ctx, emoji_sheet);
            let staged = load.into_staged(focus.as_deref(), &atlas.slot_ink);
            glyph(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
    }
}

/// Stage D: drive the Mojo glyph engine in-process over one file.
/// Prints slot count, per-load timing, throughput, and the first records.
fn run_engine_smoke(file: &Path, trie: Option<&Path>, loops: u32) {
    let default_trie = default_engine_trie();
    let trie = trie.unwrap_or(&default_trie);
    let bytes = std::fs::read(file).expect("failed to read --engine-file");

    let mut eng = engine::Engine::new();
    eng.load_trie_file(trie).expect("failed to load engine trie");

    let params = layout::ItemParams::default();
    let mut last_count = 0u64;
    let t0 = std::time::Instant::now();
    for _ in 0..loops {
        last_count = eng.load_item(&bytes, &params).expect("engine load_item failed");
    }
    let dt = t0.elapsed();

    let records = eng.read_back().records;
    assert_eq!(records.len() as u64, last_count, "record copy count mismatch");

    let total_mb = bytes.len() as f64 * loops as f64 / 1e6;
    println!(
        "engine: {} ({} B) x {} loads -> {} records in {:.3} s ({:.1} MB/s pipeline)",
        file.display(),
        bytes.len(),
        loops,
        records.len(),
        dt.as_secs_f64(),
        total_mb / dt.as_secs_f64(),
    );
    for (i, r) in records.iter().take(8).enumerate() {
        println!(
            "  rec[{}]: X={} Y={} Z={} ADVANCE={} HEIGHT={} GLYPH_ID={} ROW={} COL={}",
            i,
            r.x(),
            r.y(),
            r.z(),
            r.advance(),
            r.height(),
            r.glyph_id(),
            r.row(),
            r.col(),
        );
    }
}

/// Stage E1 cross-validation: run the engine through the FFI on `file`, then
/// independently compute the expected records with text.rs's CPU reference
/// (same atlas trie, engine fold conventions) and diff BIT-EXACT — counts and
/// measure bit patterns alike, no tolerance. Exit 1 on any divergence.
fn run_engine_check(file: &Path, trie_path: Option<&Path>) -> ! {
    let default_trie = default_engine_trie();
    let trie_path = trie_path.unwrap_or(&default_trie);
    let bytes = std::fs::read(file).expect("failed to read --engine-check file");
    let trie = atlas::TrieTable::load(&atlas_dir());

    // TWO origins, and the non-zero one is the point. At (0,0,0) an
    // uninitialised origin read is invisible: garbage added to zero on both
    // sides of the comparison agrees with itself. A Mojo nightly was caught
    // doing exactly that (see engine_item_params_at), and for a while
    // ffi_selftest was the only instrument that could see it.
    for origin in [[0.0, 0.0, 0.0], [-3.5, 11.25, 2.75]] {
        let records = engine_layout_records_at(file, trie_path, origin);
        let p = engine_item_params_at(origin);
        let expected = text::reference_layout(
            &trie,
            &bytes,
            [p.origin_x, p.origin_y, p.origin_z],
            p.line_height,
        );
        if let Err(report) = text::diff_records(&records, &expected) {
            eprintln!(
                "engine-check FAIL: {} at origin {origin:?} (trie: {})\n{report}",
                file.display(),
                trie_path.display(),
            );
            std::process::exit(1);
        }
        println!(
            "engine-check PASS: {} ({} B) at origin {origin:?} — {} records bit-exact vs the \
             CPU reference [fp contract=off verified at the dylib] (trie: {})",
            file.display(),
            bytes.len(),
            records.len(),
            trie_path.display(),
        );
    }
    std::process::exit(0);
}

/// Fixture parity: emit the canonical parse manifest, one line per fixture.
fn run_fixture_manifest(paths: &[PathBuf]) -> ! {
    for p in paths {
        match fixture::load_pipe_fixture(p) {
            Ok(fx) => println!("{}", fx.manifest()),
            Err(e) => {
                eprintln!("fixture-manifest FAIL: {e}");
                std::process::exit(1);
            }
        }
    }
    std::process::exit(0);
}

/// Bake: the bake and its seed protocol against the .bake.bin corpus.
fn run_fixture_bake(paths: &[PathBuf]) -> ! {
    let mut leaders = 0usize;
    let mut checkpoints = 0usize;
    let mut queries = 0usize;
    let mut failed = 0usize;
    for p in paths {
        let fx = match bake::load_bake_fixture(p) {
            Ok(fx) => fx,
            Err(e) => {
                eprintln!("fixture-bake FAIL: {e}");
                std::process::exit(1);
            }
        };
        let d = bake::diff_bake(&fx);
        if d.bad.is_empty() {
            println!(
                "  PASS {:<28} {} leaders / {} checkpoints / {} prefix + {} wrap queries",
                fx.name, d.leaders, d.checkpoints, d.prefix_queries, d.wrap_queries
            );
            leaders += d.leaders;
            checkpoints += d.checkpoints;
            queries += d.prefix_queries + d.wrap_queries;
        } else {
            failed += 1;
            println!("  FAIL {:<28} {} disagreement(s)", fx.name, d.bad.len());
            for line in d.bad.iter().take(8) {
                println!("       {line}");
            }
        }
    }
    if failed > 0 {
        eprintln!("fixture-bake FAIL: {failed}/{} fixtures differ", paths.len());
        std::process::exit(1);
    }
    // ANTI-VACUITY. The QUERY half is what distinguishes this from a second
    // whole-file record comparison: a bake with subtly wrong checkpoints answers
    // every total correctly and every random-access question wrongly. A run with
    // no queries would be reporting only the half that cannot see that.
    if queries == 0 {
        eprintln!("fixture-bake FAIL: no seed-protocol query was exercised");
        std::process::exit(1);
    }
    println!(
        "fixture-bake PASS: {} fixture(s), {leaders} leaders, {checkpoints} checkpoints, \
         {queries} seed-protocol queries bit-exact",
        paths.len()
    );
    std::process::exit(0);
}

/// The tunings the scan form sweeps: (chunk_size, group_size, shards).
///
/// The Mojo suite runs two — the default and one awkward pair. Being serial
/// makes more of them cheap, and each one is a different GROUPING of the same
/// monoid, so the sweep is the associativity test. The degenerate ones matter
/// most: chunk 1 makes every byte its own interval, group 1 removes the spine's
/// grouping entirely, and a large chunk makes the whole buffer one interval so
/// nothing is combined at all. `shards` is the dial on resolve_x's segment walk
/// — with one shard per item the walk NEVER fires, because the first leader of
/// an item always starts a segment.
const SCAN_TUNINGS: &[(usize, usize, usize)] = &[
    // The GPU's own defaults come from scan.rs so the sweep cannot drift from
    // the tuning the shipped path would use.
    (scan::DEFAULT_CHUNK_SIZE, scan::DEFAULT_GROUP_SIZE, 1),
    (scan::DEFAULT_CHUNK_SIZE, scan::DEFAULT_GROUP_SIZE, 4), // resolve_x shards mid-segment
    (7, 3, 3),      // seams inside multi-byte sequences AND fold units
    (1, 1, 8),      // every byte its own interval, no grouping
    (3, 1, 2),
    (1, 64, 5),
    (4096, 8, 7),   // one interval: nothing combines, everything shards
    (13, 5, 11),
];

/// Scan form: the scan form against the corpus, swept across tunings.
fn run_fixture_scan(paths: &[PathBuf]) -> ! {
    let mut failed = 0usize;
    let mut strict = 0usize;
    let mut tiered = 0usize;
    let mut cases = 0usize;
    for p in paths {
        let fx = match fixture::load_pipe_fixture(p) {
            Ok(fx) => fx,
            Err(e) => {
                eprintln!("fixture-scan FAIL: {e}");
                std::process::exit(1);
            }
        };
        let mut worst: Option<fixture::ScanDiff> = None;
        let mut ok = true;
        for &(chunk, group, shards) in SCAN_TUNINGS {
            let d = fixture::diff_scan(&fx, chunk, group, shards);
            cases += 1;
            strict += d.bit_exact_leaders;
            tiered += d.tiered_leaders;
            if !d.bad.is_empty() {
                ok = false;
                if worst.is_none() {
                    worst = Some(d);
                }
            }
        }
        if ok {
            println!("  PASS {:<26} {} tunings within the tiered contract", fx.name, SCAN_TUNINGS.len());
        } else {
            failed += 1;
            let d = worst.unwrap();
            println!(
                "  FAIL {:<26} K={}/G={}/S={} — {} mismatch(es)",
                fx.name, d.chunk_size, d.group_size, d.shards, d.bad.len()
            );
            for line in d.bad.iter().take(8) {
                println!("       {line}");
            }
        }
    }
    if failed > 0 {
        eprintln!("fixture-scan FAIL: {failed}/{} fixtures differ", paths.len());
        std::process::exit(1);
    }
    // ANTI-VACUITY. The strict tier is the load-bearing one — it is where the
    // scan claims BIT equality with the serial fold — so a run that held no
    // leader to it would be reporting the tolerant tier's green as the whole
    // result.
    if strict == 0 {
        eprintln!("fixture-scan FAIL: no leader was held to the BIT-exact tier");
        std::process::exit(1);
    }
    println!(
        "fixture-scan PASS: {} fixture(s) x {} tunings = {cases} cases; \
         {strict} leader-lanes BIT-exact, {tiered} within 1e-4 relative",
        paths.len(),
        SCAN_TUNINGS.len(),
    );
    std::process::exit(0);
}

/// Full fold: the ported fold against the whole corpus, every lane of every byte.
fn run_fixture_fold(paths: &[PathBuf]) -> ! {
    let mut lanes = 0usize;
    let mut leaders = 0usize;
    let mut failed = 0usize;
    for p in paths {
        let fx = match fixture::load_pipe_fixture(p) {
            Ok(fx) => fx,
            Err(e) => {
                eprintln!("fixture-fold FAIL: {e}");
                std::process::exit(1);
            }
        };
        let d = fixture::diff_full_fold(&fx);
        if d.bad.is_empty() {
            println!(
                "  PASS {:<26} {} bytes / {} leaders / {} lanes bit-exact",
                fx.name, d.bytes, d.leaders, d.lanes
            );
            lanes += d.lanes;
            leaders += d.leaders;
        } else {
            failed += 1;
            println!("  FAIL {:<26} {} disagreement(s)", fx.name, d.bad.len());
            for line in d.bad.iter().take(8) {
                println!("       {line}");
            }
        }
    }
    if failed > 0 {
        eprintln!("fixture-fold FAIL: {failed}/{} fixtures differ", paths.len());
        std::process::exit(1);
    }
    println!(
        "fixture-fold PASS: {} fixture(s), {leaders} leaders, {lanes} per-byte lanes \
         bit-exact vs the JS oracle",
        paths.len()
    );
    std::process::exit(0);
}

/// Trie rebuild: rebuild every fixture's trie from its bytes and diff it against the
/// one the oracle stored.
///
/// NOT a round trip: the input is the fixture's raw BYTES plus gen.mjs's pure
/// metrics function, and nothing about the stored trie's structure is handed
/// back to the builder. So the block layout, the content dedup and — the part
/// that matters — the INSERTION ORDER are all under test.
fn run_fixture_trie(paths: &[PathBuf]) -> ! {
    let mut entries = 0usize;
    let mut failed = 0usize;
    for p in paths {
        let fx = match fixture::load_pipe_fixture(p) {
            Ok(fx) => fx,
            Err(e) => {
                eprintln!("fixture-trie FAIL: {e}");
                std::process::exit(1);
            }
        };
        let r = fixture::rebuild_trie_and_diff(&fx);
        if r.bad.is_empty() {
            println!(
                "  PASS {:<26} {} entries / {} blocks / {} mapped cps — value-identical",
                fx.name, r.entries, r.block_count, r.mapped
            );
            entries += r.entries;
        } else {
            failed += 1;
            println!("  FAIL {:<26} {} disagreement(s)", fx.name, r.bad.len());
            for line in r.bad.iter().take(8) {
                println!("       {line}");
            }
        }
    }
    if failed > 0 {
        eprintln!("fixture-trie FAIL: {failed}/{} fixtures differ", paths.len());
        std::process::exit(1);
    }
    println!(
        "fixture-trie PASS: {} fixture(s), {entries} trie entries rebuilt from bytes",
        paths.len()
    );
    std::process::exit(0);
}

/// Fixture parity: hold text.rs's CPU fold to the fixture corpus, bit-exact.
///
/// Out-of-domain fixtures are SKIPPED WITH A REASON rather than silently
/// dropped, and a run in which nothing was in domain FAILS. Both halves matter:
/// this gate's whole job is comparing, and a comparison that compared nothing
/// is the loudest-passing thing there is.
fn run_fixture_reference(paths: &[PathBuf]) -> ! {
    let mut compared = 0usize;
    let mut records = 0usize;
    let mut lanes = 0usize;
    let mut failed = 0usize;
    for p in paths {
        let fx = match fixture::load_pipe_fixture(p) {
            Ok(fx) => fx,
            Err(e) => {
                eprintln!("fixture-reference FAIL: {e}");
                std::process::exit(1);
            }
        };
        let outcome = fixture::diff_against_reference_layout(&fx);
        if let Some(why) = outcome.skipped {
            println!("  SKIP {:<26} out of reference_layout domain: {why}", fx.name);
            continue;
        }
        compared += 1;
        records += outcome.records;
        lanes += outcome.compared_lanes;
        if outcome.bad.is_empty() {
            println!(
                "  PASS {:<26} {} records, {} lanes bit-exact",
                fx.name, outcome.records, outcome.compared_lanes
            );
        } else {
            failed += 1;
            print!("  FAIL {}", fixture::report(&fx, &outcome.bad, 10));
        }
    }
    if compared == 0 {
        eprintln!("fixture-reference FAIL: no fixture was in domain — nothing was compared");
        std::process::exit(1);
    }
    if failed > 0 {
        eprintln!("fixture-reference FAIL: {failed}/{compared} fixtures differ");
        std::process::exit(1);
    }
    println!(
        "fixture-reference PASS: {compared} fixture(s), {records} records, {lanes} lanes bit-exact \
         vs the oracle's expected values"
    );
    std::process::exit(0);
}

fn main() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
    let cli = parse_cli();

    // Stage H: shell completions, then exit (no GPU).
    if let Some(shell) = cli.generate {
        let mut cmd = Cli::command();
        clap_complete::generate(shell, &mut cmd, "glyph3d-native", &mut std::io::stdout());
        return;
    }

    // The hardware profile: init the GPU exactly as a render would, print,
    // exit. stdout carries only the answer (logs go to stderr), because the
    // build tool reads it to name a baseline directory.
    if cli.gpu_key || cli.gpu_profile {
        let ctx = pollster::block_on(gpu::init(None));
        if cli.gpu_key {
            println!("{}", ctx.profile.key());
        } else {
            print!("{}", ctx.profile.render_text());
        }
        return;
    }

    // Fixture parity (reference port): fixture parse manifest / corpus diff — no GPU.
    if !cli.fixture_manifest.is_empty() {
        run_fixture_manifest(&cli.fixture_manifest);
    }
    if !cli.fixture_reference.is_empty() {
        run_fixture_reference(&cli.fixture_reference);
    }
    if !cli.fixture_trie.is_empty() {
        run_fixture_trie(&cli.fixture_trie);
    }
    if !cli.fixture_fold.is_empty() {
        run_fixture_fold(&cli.fixture_fold);
    }
    if !cli.fixture_scan.is_empty() {
        run_fixture_scan(&cli.fixture_scan);
    }
    if !cli.fixture_bake.is_empty() {
        run_fixture_bake(&cli.fixture_bake);
    }

    // Stage E1: engine ↔ CPU-reference cross-check — no GPU involved.
    if let Some(file) = &cli.engine_check {
        run_engine_check(file, cli.engine_trie.as_deref());
    }

    // Stage D: Mojo engine in-process smoke test — no GPU involved.
    if let Some(file) = &cli.engine_file {
        run_engine_smoke(file, cli.engine_trie.as_deref(), cli.engine_loop);
        return;
    }

    // Stage E2 scan-only: full load pipeline without a GPU (measurement path).
    if cli.repo_scan_only {
        let dir = cli.load_repo.as_ref().expect("--repo-scan-only needs --load-repo");
        let params = repo::RepoParams {
            wrap_mode: parse_wrap_mode(&cli.wrap_mode),
            z_wrap_spacing: cli.z_wrap_spacing,
            cluster_mode: parse_cluster_mode(&cli.cluster_mode),
            ..Default::default()
        };
        let load = repo::load_repo(
            dir,
            &default_engine_trie(),
            &params,
            parse_strategy(&cli.repo_engine),
            cli.repo_verify,
        );
        load.print_stats();
        return;
    }

    let emoji_sheet = cli.emoji_sheet.clone().unwrap_or_else(default_emoji_sheet);
    let choice = if cli.demo {
        SceneChoice::Demo
    } else if let Some(dir) = &cli.load_repo {
        SceneChoice::Repo {
            dir: dir.clone(),
            strategy: parse_strategy(&cli.repo_engine),
            verify: cli.repo_verify,
            focus: cli.focus_file.clone(),
            wrap_mode: parse_wrap_mode(&cli.wrap_mode),
            z_wrap_spacing: cli.z_wrap_spacing,
            cluster_mode: parse_cluster_mode(&cli.cluster_mode),
            emoji_sheet,
        }
    } else if let Some(file) = &cli.engine_render {
        let trie = cli.engine_trie.unwrap_or_else(default_engine_trie);
        SceneChoice::EngineText {
            file: file.clone(),
            trie,
            emoji_sheet,
        }
    } else {
        SceneChoice::Text {
            file: cli.render_file.unwrap_or_else(default_text_file),
            copies: cli.copies,
            emoji_sheet,
            cluster_mode: parse_cluster_mode(&cli.cluster_mode),
        }
    };

    // Device/queue/adapter init is shared by both modes (gpu::init).
    let ctx = pollster::block_on(gpu::init(None));

    match cli.screenshot {
        Some(path) => offscreen::run(
            &ctx, &choice, &path, cli.frames, cli.zoom, !cli.no_cull, &cli.ops,
        ),
        None => {
            // Stage K (K6): scripted in-window capture (windowed only — clap
            // already rejected the combination with --screenshot).
            let shot = cli.screenshot_frame.zip(cli.screenshot_out.clone());
            windowed::run(
                ctx,
                choice,
                !cli.no_cull,
                &cli.ops,
                !cli.no_ui,
                shot,
                parse_present_mode(&cli.present_mode),
            )
        }
    }
}

