//! glyph3d-native — native GPU port of the glyph3d-js code-visualization system.
//!
//! Stage A: windowed/offscreen shell + 1M-instance quad-field stress demo.
//! Stage C: Slug analytic-coverage glyph renderer (atlas loader, WGSL Slug
//!          pipeline, text staging) behind `--render-file` (the default scene).
//! Stage F: fly camera (windowed) + per-file CPU frustum/LOD culling with
//!          far-LOD backdrop quads — the repo field is interactive.
//!          `--no-cull` keeps the legacy full-field draws for A/B.
//! Stage G: CPU picking + live manipulation. `--pick-file/--pick-row/
//!          --pick-col/--pick-px` resolve file → row/col → char; `--verb`
//!          edits instances (recolor/nudge/scale glyph, recolor line) and
//!          groups (move/scale/tint/hide) with partial buffer uploads.
//!          Windowed: left click picks, h/g/t/x verbs, right-drag look.
//! Stage H: clap CLI (parity-tested), naga WGSL validation in `cargo test`,
//!          opt-in wgpu-profiler pass timings (GLYPH_PROFILE=1), encase
//!          layout assertions for the hand-mirrored WGSL lane maps.
//! Stage I: glam 0.30 → 0.33 (byte-identical under the full A/B suite);
//!          baseline views moved onto the immutable fixtures/baseline-view.txt.
//! Stage K: egui 0.36 overlay on the windowed renderer (K1: deps + plumbing
//!          with an empty UI; `--no-ui` gives exact pre-K windowed behavior).
//!
//! Run modes:
//!   (default) `[--render-file <path>] [--copies N]`
//!                                    windowed: text field, orbiting camera, FPS log.
//!   --demo                           windowed: Stage A quad-field demo.
//!   --screenshot <path.png> [--frames N] [--zoom F] [--render-file P] [--copies N] [--demo]
//!                                    offscreen: render N frames, write PNG, print
//!                                    timing, exit 0. Deterministic (fixed virtual clock).

mod atlas;
mod bake;
mod cli;
mod cubecl_smoke;
mod cubecl_scan;
mod engine;
mod fixture;
mod fold;
mod glyph_trie;
mod layout;
mod layout_mojo;
mod gpu;
mod glyph_scene;
mod offscreen;
mod repo;
mod scan;
mod scene;
mod text;
mod windowed;

use std::path::{Path, PathBuf};

use clap::CommandFactory;
pub use cli::Op;
pub(crate) use cli::parse_verb;
use cli::{default_text_file, parse_cli, parse_cluster_mode, parse_present_mode, parse_strategy, parse_wrap_mode, Cli};
use glyph_scene::{CameraMode, GlyphScene};
use gpu::GpuContext;
// The seam is used by trait, not by concrete backend: swapping `MojoLayout`
// for the Rust one changes the constructor and nothing else here.
use layout::{LayoutGlyphs, VerifyLayout};
use scene::{Scene, SceneLike};

pub const OFFSCREEN_WIDTH: u32 = 1600;
pub const OFFSCREEN_HEIGHT: u32 = 1000;

/// Which scene a run mode builds.
pub enum SceneChoice {
    /// Stage A stress demo (1M colored quads).
    Demo,
    /// Stage C Slug text field: stage `file`, tiled `copies` times.
    Text { file: PathBuf, copies: u32, emoji_sheet: PathBuf, cluster_mode: fold::ClusterMode },
    /// Stage E1: lay `file` out with the Mojo engine (real atlas trie) and
    /// render the engine's records through the same Slug glyph renderer.
    EngineText { file: PathBuf, trie: PathBuf, emoji_sheet: PathBuf },
    /// Stage E2: load a whole repository as a field of code pages — one group
    /// per file, one shared glyph arena, grid layout.
    Repo {
        dir: PathBuf,
        strategy: layout_mojo::Strategy,
        verify: bool,
        focus: Option<String>,
        /// How a wrap is spent. `Back` is the default: a wrapped line costs
        /// DEPTH rather than a row, which is the layout this renderer is for.
        /// `repo-wide` and `repo-zoom` are gated on it; `repo-down` keeps the
        /// other mode covered so making one default cannot silently retire the
        /// other.
        wrap_mode: fold::WrapMode,
        /// The wrap staircase's pitch (`--z-wrap-spacing`, default 0.15 —
        /// the web's `zWrapSpacing`). Carried alongside wrap_mode for the
        /// same reason: the baselines depend on the default, so the CLI
        /// layer pins it rather than letting RepoParams::default speak alone.
        z_wrap_spacing: f64,
        /// The sequence pass on a repo load (`--cluster-mode`, default
        /// cluster since 2026-09-22). Same standing as wrap_mode: the
        /// baselines pin the default.
        cluster_mode: fold::ClusterMode,
        /// The colour-emoji sheet (`--emoji-sheet`; default the committed
        /// one). Every glyph scene loads it — the same handle the engine
        /// trie has, so swapping a sheet is a command-line act.
        emoji_sheet: PathBuf,
    },
}

pub fn atlas_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../assets/atlas")
}

/// Stage E1: the engine's default trie — the REAL atlas mapping, generated by
/// `python3 tools/gen_real_trie.py` (not a conformance fixture).
pub fn default_engine_trie() -> PathBuf {
    atlas_dir().join("engine-trie.bin")
}

/// The colour-emoji sheet the renderer loads unless `--emoji-sheet` says
/// otherwise — `assets/atlas/emoji-sheet.bin`, baked by tools/gen_emoji_sheet.py.
pub fn default_emoji_sheet() -> PathBuf {
    atlas_dir().join("emoji-sheet.bin")
}

/// The engine layout params the renderer/cross-check use: unit cell height
/// (text::CELL_HEIGHT_WORLD) and the production line pitch. No wrap, no pages.
/// The same params at a chosen origin.
///
/// The origin exists as a parameter because a zero one is a BLIND SPOT. A Mojo
/// nightly was found miscompiling `ffi.mojo`'s descriptor read when built into
/// a test executable — an uninitialised read — while the same source built as
/// the shipping dylib was bit-exact. `ffi_selftest` catches that class, and for
/// a while it was the ONLY thing that did, because this cross-check laid every
/// item out at (0,0,0) and so never exercised the `origin_x` read at all: a
/// garbage value added to zero and compared against zero-plus-the-same-garbage
/// agrees with itself. One instrument covering a whole failure class is a
/// single point of failure, so `--engine-check` now runs a non-zero origin too.
pub fn engine_item_params_at(origin: [f64; 3]) -> layout::ItemParams {
    layout::ItemParams {
        line_height: (text::CELL_HEIGHT_WORLD * text::LINE_HEIGHT_FACTOR) as f64,
        origin_x: origin[0],
        origin_y: origin[1],
        origin_z: origin[2],
        ..Default::default()
    }
}

/// The one item `--engine-render` and `--engine-check` each lay out: the whole
/// file, production line pitch, flat default paint, group 0.
fn engine_item(bytes: &[u8]) -> layout::LayoutItem<'_> {
    engine_item_at(bytes, [0.0, 0.0, 0.0])
}

fn engine_item_at(bytes: &[u8], origin: [f64; 3]) -> layout::LayoutItem<'_> {
    layout::LayoutItem {
        bytes,
        params: engine_item_params_at(origin),
        group_id: 0,
        paint: layout::Paint::Flat(layout::DEFAULT_COLOR_PACKED),
    }
}

fn engine_backend(trie: &Path) -> layout_mojo::MojoLayout {
    let mut backend = layout_mojo::MojoLayout::new(layout_mojo::Strategy::Batched);
    backend
        .load_trie_file(trie)
        .expect("failed to load engine trie");
    backend
}

/// Lay one file out through the seam FOR RENDERING: instances in an arena plus
/// its placement. No records, no readback — this is the path a frame takes.
fn engine_layout(file: &Path, trie: &Path) -> (layout::GlyphArena, layout::ItemPlacement) {
    let bytes = std::fs::read(file).expect("failed to read engine input file");
    let mut backend = engine_backend(trie);
    let mut arena = layout::GlyphArena::new();
    let placements = backend
        .layout_items(&[engine_item(&bytes)], &mut arena)
        .expect("engine layout failed");
    (arena, placements[0])
}

/// Lay one file out through the seam FOR VERIFICATION: the wire records, which
/// `--engine-check` diffs lane by lane against the independent CPU reference.
/// This is the 36 B-per-source-byte readback the render path above does not
/// pay, asked for explicitly through `VerifyLayout` — see `layout.rs`.
pub(crate) fn engine_layout_records_at(
    file: &Path,
    trie: &Path,
    origin: [f64; 3],
) -> Vec<layout::GlyphRecord> {
    let bytes = std::fs::read(file).expect("failed to read engine input file");
    let mut backend = engine_backend(trie);
    let mut arena = layout::GlyphArena::new();
    let (placements, records) = backend
        .layout_items_recording(&[engine_item_at(&bytes, origin)], &mut arena)
        .expect("engine layout failed");
    assert_eq!(
        records.len() as u32, placements[0].record_count,
        "record copy count mismatch"
    );
    records
}

/// Build the chosen scene for a given color target format.
pub fn build_scene(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
) -> Box<dyn SceneLike> {
    // Offscreen path: never installs a UI probe (probe = false), so the
    // scene behaves exactly as pre-K.
    build_scene_impl(ctx, color_format, choice, camera_mode, cull, false).0
}

/// Stage K (K3): windowed scene construction. Same scenes as build_scene,
/// plus a debug-UI probe handle installed on the concrete GlyphScene BEFORE
/// type erasure — the egui Debug panel's read-back channel (windowed.rs
/// holds the scene as `Box<dyn SceneLike>`; fence 4 forbids SceneLike
/// changes). The demo scene has no probe (None).
pub fn build_scene_probed(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
) -> (Box<dyn SceneLike>, Option<glyph_scene::UiProbe>) {
    build_scene_impl(ctx, color_format, choice, camera_mode, cull, true)
}

fn build_scene_impl(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
    probe: bool,
) -> (Box<dyn SceneLike>, Option<glyph_scene::UiProbe>) {
    // Same construction order for both modes; only the probe install differs.
    let glyph = |scene: GlyphScene| {
        let mut scene = scene;
        let p = probe.then(|| scene.init_ui_probe());
        (Box::new(scene) as Box<dyn SceneLike>, p)
    };
    match choice {
        SceneChoice::Demo => (Box::new(Scene::new(ctx, color_format)), None),
        SceneChoice::Text { file, copies, emoji_sheet, cluster_mode } => {
            let atlas = atlas::Atlas::load(ctx, emoji_sheet);
            let staged = text::stage_file(&atlas, file, *copies, *cluster_mode);
            log::info!(
                "staged {}: {} codepoints → {} glyph instances ({} copies, {} missing/bitmap)",
                file.display(),
                staged.codepoints_decoded,
                staged.glyphs_emitted,
                copies,
                staged.missing_or_bitmap,
            );
            let mut scene = GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull);
            // No pick context on this path, so the panel's cluster toggle
            // seeds from the choice directly — hand it the mode the scene
            // was staged with.
            scene.set_probe_cluster_mode(matches!(cluster_mode, fold::ClusterMode::Cluster));
            glyph(scene)
        }
        SceneChoice::EngineText { file, trie, emoji_sheet } => {
            let atlas = atlas::Atlas::load(ctx, emoji_sheet);
            let (arena, placement) = engine_layout(file, trie);
            log::info!(
                "engine-staged {}: {} records ({} blank/missing slots dropped)",
                file.display(),
                placement.record_count,
                placement.record_count - placement.slot_count,
            );
            let staged = text::stage_records(arena, &placement, &atlas.slot_ink);
            glyph(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
        SceneChoice::Repo {
            dir,
            strategy,
            verify,
            focus,
            wrap_mode,
            z_wrap_spacing,
            cluster_mode,
            emoji_sheet,
        } => {
            let params = repo::RepoParams {
                wrap_mode: *wrap_mode,
                z_wrap_spacing: *z_wrap_spacing,
                cluster_mode: *cluster_mode,
                ..Default::default()
            };
            let load = {
                let walk = repo::walk_repo(dir);
                // The device-resident arena: the FFI writes instances into
                // the same shared-storage buffer the shader reads. Direct
                // only (it's the strategy with the tail-write protocol), on
                // unified memory, when the buffer fits.
                let arena = if *strategy == layout_mojo::Strategy::Direct
                    && ctx.profile.backend == wgpu::Backend::Metal
                    && ctx.profile.mappable_primary_buffers
                    && walk.total_bytes > 0
                    && (walk.total_bytes * std::mem::size_of::<glyph_scene::GlyphInstance>()) as u64
                        <= ctx.profile.max_buffer_size
                {
                    glyph_scene::mapped_instance_arena(ctx, walk.total_bytes)
                } else {
                    layout::GlyphArena::new()
                };
                repo::load_repo_from_walk(dir, walk, &default_engine_trie(), &params, *strategy, *verify, arena)
            };
            load.print_stats();
            let atlas = atlas::Atlas::load(ctx, emoji_sheet);
            let staged = load.into_staged(focus.as_deref(), &atlas.slot_ink);
            glyph(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
    }
}

/// Stage D: drive the Mojo glyph engine in-process over one file.
/// Prints slot count, per-load timing, throughput, and the first records.
fn main() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
    let cli = parse_cli();

    // Stage H: shell completions, then exit (no GPU).
    if let Some(shell) = cli.generate {
        let mut cmd = Cli::command();
        clap_complete::generate(shell, &mut cmd, "glyph3d-native", &mut std::io::stdout());
        return;
    }

    // The hardware profile: init the GPU exactly as a render would, print,
    // exit. stdout carries only the answer (logs go to stderr), because the
    // build tool reads it to name a baseline directory.
    if cli.gpu_key || cli.gpu_profile {
        let ctx = pollster::block_on(gpu::init(None));
        if cli.gpu_key {
            println!("{}", ctx.profile.key());
        } else {
            print!("{}", ctx.profile.render_text());
        }
        return;
    }

    // Dev-only CubeCL bring-up smoke (note 16, phase 0).
    if cli.cubecl_smoke {
        let ctx = pollster::block_on(gpu::init(None));
        cubecl_smoke::run(&ctx);
    }
    // Dev-only CubeCL scan check (note 16, phase 1).
    if let Some(path) = &cli.cubecl_scan_check {
        let ctx = pollster::block_on(gpu::init(None));
        cubecl_scan::run(&ctx, path);
    }

    // Fixture parity (reference port): fixture parse manifest / corpus diff — no GPU.
    if !cli.fixture_manifest.is_empty() {
        fixture::run_fixture_manifest(&cli.fixture_manifest);
    }
    if !cli.fixture_reference.is_empty() {
        fixture::run_fixture_reference(&cli.fixture_reference);
    }
    if !cli.fixture_trie.is_empty() {
        fixture::run_fixture_trie(&cli.fixture_trie);
    }
    if !cli.fixture_fold.is_empty() {
        fixture::run_fixture_fold(&cli.fixture_fold);
    }
    if !cli.fixture_scan.is_empty() {
        scan::run_fixture_scan(&cli.fixture_scan);
    }
    if !cli.fixture_bake.is_empty() {
        bake::run_fixture_bake(&cli.fixture_bake);
    }

    // Stage E1: engine ↔ CPU-reference cross-check — no GPU involved.
    if let Some(file) = &cli.engine_check {
        engine::run_engine_check(file, cli.engine_trie.as_deref());
    }

    // Stage D: Mojo engine in-process smoke test — no GPU involved.
    if let Some(file) = &cli.engine_file {
        engine::run_engine_smoke(file, cli.engine_trie.as_deref(), cli.engine_loop);
        return;
    }

    // Stage E2 scan-only: full load pipeline without a GPU (measurement path).
    if cli.repo_scan_only {
        let dir = cli.load_repo.as_ref().expect("--repo-scan-only needs --load-repo");
        let params = repo::RepoParams {
            wrap_mode: parse_wrap_mode(&cli.wrap_mode),
            z_wrap_spacing: cli.z_wrap_spacing,
            cluster_mode: parse_cluster_mode(&cli.cluster_mode),
            ..Default::default()
        };
        let load = repo::load_repo(
            dir,
            &default_engine_trie(),
            &params,
            parse_strategy(&cli.repo_engine),
            cli.repo_verify,
        );
        load.print_stats();
        return;
    }

    let emoji_sheet = cli.emoji_sheet.clone().unwrap_or_else(default_emoji_sheet);
    let choice = if cli.demo {
        SceneChoice::Demo
    } else if let Some(dir) = &cli.load_repo {
        SceneChoice::Repo {
            dir: dir.clone(),
            strategy: parse_strategy(&cli.repo_engine),
            verify: cli.repo_verify,
            focus: cli.focus_file.clone(),
            wrap_mode: parse_wrap_mode(&cli.wrap_mode),
            z_wrap_spacing: cli.z_wrap_spacing,
            cluster_mode: parse_cluster_mode(&cli.cluster_mode),
            emoji_sheet,
        }
    } else if let Some(file) = &cli.engine_render {
        let trie = cli.engine_trie.unwrap_or_else(default_engine_trie);
        SceneChoice::EngineText {
            file: file.clone(),
            trie,
            emoji_sheet,
        }
    } else {
        SceneChoice::Text {
            file: cli.render_file.unwrap_or_else(default_text_file),
            copies: cli.copies,
            emoji_sheet,
            cluster_mode: parse_cluster_mode(&cli.cluster_mode),
        }
    };

    // Device/queue/adapter init is shared by both modes (gpu::init).
    let ctx = pollster::block_on(gpu::init(None));

    match cli.screenshot {
        Some(path) => offscreen::run(
            &ctx, &choice, &path, cli.frames, cli.zoom, !cli.no_cull, &cli.ops,
        ),
        None => {
            // Stage K (K6): scripted in-window capture (windowed only — clap
            // already rejected the combination with --screenshot).
            let shot = cli.screenshot_frame.zip(cli.screenshot_out.clone());
            windowed::run(
                ctx,
                choice,
                !cli.no_cull,
                &cli.ops,
                !cli.no_ui,
                shot,
                parse_present_mode(&cli.present_mode),
            )
        }
    }
}

