//! glyph3d-native — native GPU port of the glyph3d-js code-visualization system.
//!
//! Stage A: windowed/offscreen shell + 1M-instance quad-field stress demo.
//! Stage C: Slug analytic-coverage glyph renderer (atlas loader, WGSL Slug
//!          pipeline, text staging) behind `--render-file` (the default scene).
//! Stage F: fly camera (windowed) + per-file CPU frustum/LOD culling with
//!          far-LOD backdrop quads — the repo field is interactive.
//!          `--no-cull` keeps the legacy full-field draws for A/B.
//!
//! Run modes:
//!   (default) [--render-file <path>] [--copies N]
//!                                    windowed: text field, orbiting camera, FPS log.
//!   --demo                           windowed: Stage A quad-field demo.
//!   --screenshot <path.png> [--frames N] [--zoom F] [--render-file P] [--copies N] [--demo]
//!                                    offscreen: render N frames, write PNG, print
//!                                    timing, exit 0. Deterministic (fixed virtual clock).

mod atlas;
mod engine;
mod gpu;
mod glyph_scene;
mod offscreen;
mod repo;
mod scene;
mod text;
mod windowed;

use std::path::{Path, PathBuf};

use glyph_scene::{CameraMode, GlyphScene};
use gpu::GpuContext;
use scene::{Scene, SceneLike};

pub const OFFSCREEN_WIDTH: u32 = 1600;
pub const OFFSCREEN_HEIGHT: u32 = 1000;

/// Which scene a run mode builds.
pub enum SceneChoice {
    /// Stage A stress demo (1M colored quads).
    Demo,
    /// Stage C Slug text field: stage `file`, tiled `copies` times.
    Text { file: PathBuf, copies: u32 },
    /// Stage E1: lay `file` out with the Mojo engine (real atlas trie) and
    /// render the engine's records through the same Slug glyph renderer.
    EngineText { file: PathBuf, trie: PathBuf },
    /// Stage E2: load a whole repository as a field of code pages — one group
    /// per file, one shared glyph arena, grid layout.
    Repo {
        dir: PathBuf,
        batch: bool,
        verify: bool,
        focus: Option<String>,
    },
}

/// The atlas directory shared by every mode (`<crate>/../assets/atlas`).
pub fn atlas_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../assets/atlas")
}

/// Stage E1: the engine's default trie — the REAL atlas mapping, generated by
/// `node tools/gen-real-trie.mjs` (not a conformance fixture).
pub fn default_engine_trie() -> PathBuf {
    atlas_dir().join("engine-trie.bin")
}

/// The engine layout params the renderer/cross-check use: unit cell height
/// (text::CELL_HEIGHT_WORLD) and the production line pitch. No wrap, no pages.
pub fn engine_item_params() -> engine::ItemParams {
    engine::ItemParams {
        line_height: (text::CELL_HEIGHT_WORLD * text::LINE_HEIGHT_FACTOR) as f64,
        ..Default::default()
    }
}

/// Run the Mojo engine over one file and return its records.
fn engine_layout(file: &Path, trie: &Path) -> Vec<engine::GlyphRecord> {
    let bytes = std::fs::read(file).expect("failed to read engine input file");
    let mut eng = engine::Engine::new();
    eng.load_trie_file(trie).expect("failed to load engine trie");
    let n = eng
        .load_item(&bytes, &engine_item_params())
        .expect("engine load_item failed");
    let records = eng.records();
    assert_eq!(records.len() as u64, n, "record copy count mismatch");
    records
}

/// Build the chosen scene for a given color target format.
pub fn build_scene(
    ctx: &GpuContext,
    color_format: wgpu::TextureFormat,
    choice: &SceneChoice,
    camera_mode: CameraMode,
    cull: bool,
) -> Box<dyn SceneLike> {
    match choice {
        SceneChoice::Demo => Box::new(Scene::new(ctx, color_format)),
        SceneChoice::Text { file, copies } => {
            let atlas = atlas::Atlas::load(ctx);
            let staged = text::stage_file(&atlas, file, *copies);
            log::info!(
                "staged {}: {} codepoints → {} glyph instances ({} copies, {} missing/bitmap)",
                file.display(),
                staged.codepoints_decoded,
                staged.glyphs_emitted,
                copies,
                staged.missing_or_bitmap,
            );
            Box::new(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
        SceneChoice::EngineText { file, trie } => {
            let atlas = atlas::Atlas::load(ctx);
            let records = engine_layout(file, trie);
            log::info!(
                "engine-staged {}: {} records ({} blank/missing slots dropped)",
                file.display(),
                records.len(),
                records.iter().filter(|r| r.glyph_id() == 0).count(),
            );
            let staged = text::stage_records(&records);
            Box::new(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
        SceneChoice::Repo {
            dir,
            batch,
            verify,
            focus,
        } => {
            let params = repo::RepoParams::default();
            let load = repo::load_repo(dir, &default_engine_trie(), &params, *batch, *verify);
            load.print_stats();
            let atlas = atlas::Atlas::load(ctx);
            let staged = load.into_staged(focus.as_deref());
            Box::new(GlyphScene::new(ctx, color_format, &atlas, staged, camera_mode, cull))
        }
    }
}

struct Cli {
    screenshot: Option<PathBuf>,
    frames: u32,
    demo: bool,
    render_file: Option<PathBuf>,
    copies: u32,
    zoom: f32,
    /// Stage D: run the Mojo glyph engine in-process on this file and exit.
    engine_file: Option<PathBuf>,
    /// Trie for the engine modes (default: assets/atlas/engine-trie.bin —
    /// the real atlas mapping; pass a .pipe.bin fixture for the toy one).
    engine_trie: Option<PathBuf>,
    /// Repeat the load N times (leak/stability loop for --engine-file).
    engine_loop: u32,
    /// Stage E1: cross-check --engine-file output against text.rs's CPU
    /// reference layout (bit-exact) and exit.
    engine_check: Option<PathBuf>,
    /// Stage E1: render engine records through the Slug renderer.
    engine_render: Option<PathBuf>,
    /// Stage E2: load a whole repository as a field of code pages.
    load_repo: Option<PathBuf>,
    /// Stage E2: engine path for repo loads — "naive" (default; measured
    /// faster on the 97 MB corpus — see out/STAGE_E2_REPORT.md) or "batch".
    repo_engine: String,
    /// Stage E2: diff batch vs naive bit-exact over the whole repo.
    repo_verify: bool,
    /// Stage E2: frame the first file whose path contains this substring.
    focus_file: Option<String>,
    /// Stage E2: walk + engine + stage + stats, then exit (no GPU).
    repo_scan_only: bool,
    /// Stage F: disable the cull/LOD pass (legacy per-chunk draws; debug/A-B).
    no_cull: bool,
}

fn parse_cli() -> Cli {
    // Minimal hand-rolled parser; this is a dev/verification tool, not a product CLI.
    let mut cli = Cli {
        screenshot: None,
        frames: 1,
        demo: false,
        render_file: None,
        copies: 1,
        zoom: 1.0,
        engine_file: None,
        engine_trie: None,
        engine_loop: 1,
        engine_check: None,
        engine_render: None,
        load_repo: None,
        repo_engine: "naive".to_string(),
        repo_verify: false,
        focus_file: None,
        repo_scan_only: false,
        no_cull: false,
    };
    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--screenshot" => {
                let path = args
                    .next()
                    .expect("--screenshot requires a path argument, e.g. --screenshot out.png");
                cli.screenshot = Some(PathBuf::from(path));
            }
            "--frames" => {
                let n = args.next().expect("--frames requires a count");
                cli.frames = n.parse().expect("--frames must be a positive integer");
            }
            "--demo" => cli.demo = true,
            "--render-file" => {
                let path = args.next().expect("--render-file requires a path argument");
                cli.render_file = Some(PathBuf::from(path));
            }
            "--copies" => {
                let n = args.next().expect("--copies requires a count");
                cli.copies = n.parse().expect("--copies must be a positive integer");
            }
            "--zoom" => {
                let z = args.next().expect("--zoom requires a factor");
                cli.zoom = z.parse().expect("--zoom must be a positive number");
            }
            "--engine-file" => {
                let path = args.next().expect("--engine-file requires a path argument");
                cli.engine_file = Some(PathBuf::from(path));
            }
            "--engine-trie" => {
                let path = args.next().expect("--engine-trie requires a path argument");
                cli.engine_trie = Some(PathBuf::from(path));
            }
            "--engine-loop" => {
                let n = args.next().expect("--engine-loop requires a count");
                cli.engine_loop = n.parse().expect("--engine-loop must be a positive integer");
            }
            "--engine-check" => {
                let path = args.next().expect("--engine-check requires a path argument");
                cli.engine_check = Some(PathBuf::from(path));
            }
            "--engine-render" => {
                let path = args.next().expect("--engine-render requires a path argument");
                cli.engine_render = Some(PathBuf::from(path));
            }
            "--load-repo" => {
                let path = args.next().expect("--load-repo requires a directory argument");
                cli.load_repo = Some(PathBuf::from(path));
            }
            "--repo-engine" => {
                let mode = args.next().expect("--repo-engine requires naive|batch");
                assert!(mode == "naive" || mode == "batch", "--repo-engine must be naive|batch");
                cli.repo_engine = mode;
            }
            "--repo-verify" => cli.repo_verify = true,
            "--focus-file" => {
                let s = args.next().expect("--focus-file requires a path substring");
                cli.focus_file = Some(s);
            }
            "--repo-scan-only" => cli.repo_scan_only = true,
            "--no-cull" => cli.no_cull = true,
            "-h" | "--help" => {
                eprintln!(
                    "usage: glyph3d-native [options]\n\
                     \x20 no args              windowed text field (default file: this crate's main.rs)\n\
                     \x20 --demo               Stage A quad-field demo instead of the text field\n\
                     \x20 --render-file PATH   text file to stage (UTF-8)\n\
                     \x20 --copies N           tile the file N times (stress; default 1)\n\
                     \x20 --screenshot PATH    offscreen render -> PNG, then exit\n\
                     \x20 --frames N           frames to render offscreen (default 1)\n\
                     \x20 --zoom F             camera magnification for offscreen (default 1)\n\
                     \x20 --engine-file PATH   run the Mojo engine on PATH, print records, exit\n\
                     \x20 --engine-trie PATH   trie for engine modes (default: assets/atlas/engine-trie.bin)\n\
                     \x20 --engine-loop N      repeat --engine-file load N times\n\
                     \x20 --engine-check PATH  cross-check engine output vs text.rs CPU reference\n\
                     \x20 --engine-render PATH render engine records through the Slug renderer\n\
                     \x20 --load-repo DIR      Stage E2: load a whole repo as a field of code pages\n\
                     \x20 --repo-engine MODE   repo engine path: naive (default) | batch\n\
                     \x20 --repo-verify        diff batch vs naive bit-exact over the repo\n\
                     \x20 --focus-file SUBSTR  frame the first file whose path contains SUBSTR\n\
                     \x20 --repo-scan-only     walk+engine+stage+stats, no GPU, then exit\n\
                     \x20 --no-cull            Stage F: disable cull/LOD (legacy full-field draws)\n\
                     \x20 windowed mode: fly camera — click to grab the mouse, WASD move,\n\
                     \x20   E|R up, Q|F down, mouse-look, scroll = speed, Esc releases"
                );
                std::process::exit(0);
            }
            other => {
                eprintln!("unknown argument: {other} (try --help)");
                std::process::exit(2);
            }
        }
    }
    cli
}

fn default_text_file() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("src/main.rs")
}

/// Stage D: drive the Mojo glyph engine in-process over one file.
/// Prints slot count, per-load timing, throughput, and the first records.
fn run_engine_smoke(file: &Path, trie: Option<&Path>, loops: u32) {
    let default_trie = default_engine_trie();
    let trie = trie.unwrap_or(&default_trie);
    let bytes = std::fs::read(file).expect("failed to read --engine-file");

    let mut eng = engine::Engine::new();
    eng.load_trie_file(trie).expect("failed to load engine trie");

    let params = engine::ItemParams::default();
    let mut last_count = 0u64;
    let t0 = std::time::Instant::now();
    for _ in 0..loops {
        last_count = eng.load_item(&bytes, &params).expect("engine load_item failed");
    }
    let dt = t0.elapsed();

    let records = eng.records();
    assert_eq!(records.len() as u64, last_count, "record copy count mismatch");

    let total_mb = bytes.len() as f64 * loops as f64 / 1e6;
    println!(
        "engine: {} ({} B) x {} loads -> {} records in {:.3} s ({:.1} MB/s pipeline)",
        file.display(),
        bytes.len(),
        loops,
        records.len(),
        dt.as_secs_f64(),
        total_mb / dt.as_secs_f64(),
    );
    for (i, r) in records.iter().take(8).enumerate() {
        println!(
            "  rec[{}]: X={} Y={} Z={} ADVANCE={} HEIGHT={} GLYPH_ID={} ROW={} COL={}",
            i,
            r.x(),
            r.y(),
            r.z(),
            r.advance(),
            r.height(),
            r.glyph_id(),
            r.row(),
            r.col(),
        );
    }
}

/// Stage E1 cross-validation: run the engine through the FFI on `file`, then
/// independently compute the expected records with text.rs's CPU reference
/// (same atlas trie, engine fold conventions) and diff BIT-EXACT — counts and
/// measure bit patterns alike, no tolerance. Exit 1 on any divergence.
fn run_engine_check(file: &Path, trie_path: Option<&Path>) -> ! {
    let default_trie = default_engine_trie();
    let trie_path = trie_path.unwrap_or(&default_trie);
    let bytes = std::fs::read(file).expect("failed to read --engine-check file");

    let records = engine_layout(file, trie_path);

    // The independent side: CPU layout straight from the atlas export,
    // no engine involvement. Same params as engine_layout.
    let trie = atlas::TrieTable::load(&atlas_dir());
    let p = engine_item_params();
    let expected = text::reference_layout(
        &trie,
        &bytes,
        [p.origin_x, p.origin_y, p.origin_z],
        p.line_height,
    );

    match text::diff_records(&records, &expected) {
        Ok(()) => {
            println!(
                "engine-check PASS: {} ({} B) — {} records bit-exact vs the CPU reference \
                 (trie: {})",
                file.display(),
                bytes.len(),
                records.len(),
                trie_path.display(),
            );
            std::process::exit(0);
        }
        Err(report) => {
            eprintln!(
                "engine-check FAIL: {} (trie: {})\n{report}",
                file.display(),
                trie_path.display(),
            );
            std::process::exit(1);
        }
    }
}

fn main() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
    let cli = parse_cli();

    // Stage E1: engine ↔ CPU-reference cross-check — no GPU involved.
    if let Some(file) = &cli.engine_check {
        run_engine_check(file, cli.engine_trie.as_deref());
    }

    // Stage D: Mojo engine in-process smoke test — no GPU involved.
    if let Some(file) = &cli.engine_file {
        run_engine_smoke(file, cli.engine_trie.as_deref(), cli.engine_loop);
        return;
    }

    // Stage E2 scan-only: full load pipeline without a GPU (measurement path).
    if cli.repo_scan_only {
        let dir = cli.load_repo.as_ref().expect("--repo-scan-only needs --load-repo");
        let params = repo::RepoParams::default();
        let load = repo::load_repo(
            dir,
            &default_engine_trie(),
            &params,
            cli.repo_engine == "batch",
            cli.repo_verify,
        );
        load.print_stats();
        return;
    }

    let choice = if cli.demo {
        SceneChoice::Demo
    } else if let Some(dir) = &cli.load_repo {
        SceneChoice::Repo {
            dir: dir.clone(),
            batch: cli.repo_engine == "batch",
            verify: cli.repo_verify,
            focus: cli.focus_file.clone(),
        }
    } else if let Some(file) = &cli.engine_render {
        let trie = cli.engine_trie.unwrap_or_else(default_engine_trie);
        SceneChoice::EngineText {
            file: file.clone(),
            trie,
        }
    } else {
        SceneChoice::Text {
            file: cli.render_file.unwrap_or_else(default_text_file),
            copies: cli.copies,
        }
    };

    // Device/queue/adapter init is shared by both modes (gpu::init).
    let ctx = pollster::block_on(gpu::init(None));

    match cli.screenshot {
        Some(path) => offscreen::run(&ctx, &choice, &path, cli.frames, cli.zoom, !cli.no_cull),
        None => windowed::run(ctx, &choice, !cli.no_cull),
    }
}
